# Project 1 -- Seyi Ogunmodede

**TA Help:** Jackson Mathew, Siddharth Singh, Tong En Sim

- Help with templates and the project to start with.
- Help to navigate the right project to do
- Help with ensuring that each cell is run to avoid syntax error
    
**Collaboration:** 

## Question 1

In [ ]:
# code here

In the sub cluster on anvil, since there are three of them (A, B & C), 134144 cores in total (128 * 1000, 128 * 32, 128 * 16) with total memory of 296.192TB (1000 * 266GB, 32 * 1TB, 16 * 512GB).

My computer has 12 Cores, Installed Physical Memory (RAM) 16.0 GB, Total Physical Memory 15.7 GB, Available Physical Memory 5.94 GB, Total Virtual Memory 18.1 GB, Available Virtual Memory 4.09 GB, and Page File Space 2.38 GB.

## Question 2

In [1]:
%%R

system("hostname", intern=TRUE)

[1] "a240.anvil.rcac.purdue.edu"


The name of the node on Anvil that you are running on is "a240.anvil.rcac.purdue.edu"

## Question 3

In [2]:
my_list = [1, 2, 3]
print(f'My list is: {my_list}')

My list is: [1, 2, 3]


My list consist of 1, 2, 3, variables.

## Question 4

There are five each types of cells in the default template.

## Question 5

In [7]:
# Subcluster A
%%R

1000 * 128

[1] 128000


In [8]:
# Subcluster B
%%R

32 * 128

[1] 4096


In [9]:
# Subcluster G
%%R

16 * 128

[1] 2048


In [10]:
%%R

128000+4096+2048

[1] 134144


 In the sub cluster on anvil, since there are three of them (A, B & C), there are 134144 (128000 + 4096 +2048) cores using R. 

In [4]:
# Subcluster A
%%R

1000*256

[1] 256000


In [14]:
# Subcluster B
%%R

32*1

[1] 32


In [15]:
# Subcluster G
%%R

16*512

[1] 8192


In [3]:
%%R

256000+32000+8192

[1] 296192


 In the sub cluster on anvil, since there are three of them (A, B & C), there are 296.192TB (256000GB + 32TB + 8192GB) using R.

In [1]:
# Subcluster A
1000 * 128

128000

In [2]:
# Subcluster A
32 * 128

4096

In [3]:
# Subcluster A
16 * 128

2048

In [10]:
128000+4096+2048

[1] 134144


 In the sub cluster on anvil, since there are three of them (A, B & C), there are 134144 (128000 + 4096 +2048) cores using Python 

In [5]:
# Subcluster A
1000*256

256000

In [6]:
# Subcluster A
32 * 1

32

In [7]:
# Subcluster A
16 * 512

8192

In [3]:
256000+32000+8192

[1] 296192


 In the sub cluster on anvil, since there are three of them (A, B & C), there are 296.192TB (256000GB + 32TB + 8192GB)

## Question 6

In [2]:
%%R

dat <- read.csv("/anvil/projects/tdm/data/disney/flight_of_passage.csv")

In [3]:
%%R

head(dat)


        date            datetime SACTMIN SPOSTMIN
1 05/26/2017 2017-05-26 09:06:38      NA     -999
2 05/26/2017 2017-05-26 09:10:11      47       NA
3 05/26/2017 2017-05-26 09:10:12      NA        5
4 05/26/2017 2017-05-26 09:17:09      NA       60
5 05/26/2017 2017-05-26 09:24:07      NA       60
6 05/26/2017 2017-05-26 09:30:10      NA       60


In [4]:
%%R

flight_of_passage <- read.csv("/anvil/projects/tdm/data/disney/flight_of_passage.csv")

In [5]:
%%R

head(flight_of_passage)

        date            datetime SACTMIN SPOSTMIN
1 05/26/2017 2017-05-26 09:06:38      NA     -999
2 05/26/2017 2017-05-26 09:10:11      47       NA
3 05/26/2017 2017-05-26 09:10:12      NA        5
4 05/26/2017 2017-05-26 09:17:09      NA       60
5 05/26/2017 2017-05-26 09:24:07      NA       60
6 05/26/2017 2017-05-26 09:30:10      NA       60


## Pledge

By submitting this work I hereby pledge that this is my own, personal work. I've acknowledged in the designated place at the top of this file all sources that I used to complete said work, including but not limited to: online resources, books, and electronic communications. I've noted all collaboration with fellow students and/or TA's. I did not copy or plagiarize another's work.

> As a Boilermaker pursuing academic excellence, I pledge to be honest and true in all that I do. Accountable together – We are Purdue.